* Notes and thoughts
- This is on a REALLY early stage of development.
- I deleted the visual state from Evil, I don't really know if that was a good idea. Setting keys for that state maybe is overwhelming.
- If you come from Evil:
  - This packages removes VISUAL state.
  - EVIL-EX is not part of this project

* What is this?
Nsevil (Not so evil) is a fork of [[https://github.com/emacs-evil/evil/][emacs evil]] with multiples major changes and a little inspiration on [[https://github.com/mrkkrp/modalka][Modalka]].
** What is not
This does't want to be a Vim emulator. It's more similar to a different approach of Modalka.
** Diferences
The idea is to introduce modal editing en Emacs, but with some major differences with Modalka and Evil:
1. Not define ANY key. By default this package will only define two editing modes. Insert and Command. The command map will be totally empy (You set what you use).
2. Not define fanccy functions. I don't really like how Evil modify Emacs editing behavior.
3. Comparing with Modalka this doesn't touch the global keymap. When this minor mode is enabled current keymap can be switched back (As Evil do).
** Usage
Install from Melpa and add to your =init.el=

#+begin_src emacs-lisp
(require 'nsevil)
(nsevil-mode 1)
#+end_src
*** Defining keys:
As fork of Evil the keys definitions are practical the same:

#+begin_src emacs-lisp
;; Normal map
(define-key nsevil-normal-state-map "i" 'nsevil-insert)
(define-key nsevil-normal-state-map "f" 'forward-char)
;; Insert map
(define-key nsevil-insert-state-map [escape] 'nsevil-normal-state)
(define-key nsevil-insert-state-map (kbd "C-z") 'avy-goto-char)
#+end_src

* Want to contribute?
I'm not a relly elisp programmer, so any help is appreciated. From bug report to pull request. Don't know how to ccontribute? Here is a list of things that I want to do/implement:
- [ ] Review all code: Maybe I forgot some Evil code that is never used or I deleted some useful code.
- [X] Delete ALL the keys from command mode. I want to be a totally clean map and the user define what it want.
- [ ] As I'm not so familiar with Evil yet I don't know if there is a 'shared' keymap. Usefull for commands that we want on insert and normal state.
- [ ] Make a better README. As non-english native speaker this readme isn't good at all. I want to expand it and add more code and examples

* Contributors and license
 As fork of Evil the majority of the code isn't mine on this stage. See [[https://github.com/NicolasIriarte/nsevil/blob/master/nsevil.el][this]] file for a list of the original contributors.

 Nsevil (Not So Evil) as Evil respect the GPL-3.0 License.
